---
- name: "Create new log group for the app"
  cloudwatchlogs_log_group:
    log_group_name: timeapp_cl_log_group
    retention: 1

- name: "Register the task definition for the containers"
  ecs_taskdefinition:
    family: ans-time-app
    cpu: 256
    memory: 512
    network_mode: awsvpc
    execution_role_arn: "{{ iam_role.arn }}"
    launch_type: FARGATE
    containers:
      - name: ans-time-app
        image: "741564014416.dkr.ecr.eu-west-1.amazonaws.com/engagetech"
        cpu: 256
        memory: 512
        portMappings:
          - containerPort: 8080
        logConfiguration:
          logDriver: awslogs
          options:
            awslogs-group: timeapp_cl_log_group
            awslogs-region: "{{ aws_region }}"
            awslogs-stream-prefix: 'ans-timeapp-'
    state: present
  register: ansl_time_app_task

- name: "Set facts: Task definition"
  set_fact:
    ecs_task: "{{ ansl_time_app_task }}"
