AWSTemplateFormatVersion: '2010-09-09'
Description: "Definition for the task with the image to use"
Resources:
  # Define the task with the already uploaded image to AWS ECS Registry
  TimeAppTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: timeapp
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue ECSTaskExecutionRole
      ContainerDefinitions:
        - Name: timeapp
          Image: 741564014416.dkr.ecr.eu-west-1.amazonaws.com/engagetech
          Cpu: 256
          Memory: 512
          PortMappings:
            - ContainerPort: 8080
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: 'timeapp'
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: 'timeapp'

Outputs:
  TimeAppTask:
    Description: 'The registered task for our tiem app'
    Value: !Ref TimeAppTask
    Export:
      Name: 'TimeAppTask'
